name: 'Prepare Docker Buildx environment'
description: 'Downloads and extracts the TagLib library, adding it to PKG_CONFIG_PATH'
inputs:
  platform:
    description: 'Platform to download TagLib for'
    required: true
outputs:
  tags:
    description: 'Docker image tags'
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: 'Docker image labels'
    value: ${{ steps.meta.outputs.labels }}
  annotations:
    description: 'Docker image annotations'
    value: ${{ steps.meta.outputs.annotations }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Check Docker Hub configuration
      shell: bash
      run: |
        if [ -z "${{vars.DOCKER_HUB_REPO}}${{secrets.DOCKER_USERNAME}}${{secrets.DOCKER_PASSWORD}}" ]; then
          echo "DOCKER_HUB_REPO=none" >> $GITHUB_ENV
          echo "DOCKER_HUB_ENABLED=false" >> $GITHUB_ENV
        else
          echo "DOCKER_HUB_REPO=${{vars.DOCKER_HUB_REPO}}" >> $GITHUB_ENV
          echo "DOCKER_HUB_ENABLED=true" >> $GITHUB_ENV
        fi

    - name: Extract metadata for Docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        labels: |
          maintainer=deluan@navidrome.org
        images: |
          name=${{env.DOCKER_HUB_REPO}},enable=${{env.DOCKER_HUB_ENABLED}}
          name=ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=raw,value=develop,enable={{is_default_branch}}

    - name: Login to Docker Hub
      if: env.DOCKER_HUB_ENABLED == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
